sudo: required
services:
  - docker
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
language: node_js
node_js:
  - "8.12.0"
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - make setup
script:
  - make run_ci
  - make setup_db
  - make test
notifications:
  email: false
