sudo: required
services:
  - docker
language: node_js
node_js:
  - "8.12.0"
cache: yarn
install:
  - make setup
script:
  - make run_ci
  - make setup_db
  - make test
notifications:
  email: false
addons:
  chrome: stable
