sudo: required
services:
  - docker
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
language: node_js
node_js:
  - "8.12.0"
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - make setup
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - make run_ci
  - make setup_db
  - make test
notifications:
  email: false
